### ISSUE TITLE
group key ~> latest 1 ~> value

### ISSUE THREAD

**Issue by HuwCampbell** [ambiata/icicle#107]
Grouping on a key doesn't currently allow one to select just the latest, that is, one can't implement LatestBy.
Bubblegum should stick onto to the latest in each group.

**Comment by amosr** [comment]
Vague thoughts: this requires a change to Core, but I think Avalanche can be kept more or less the same.

Perhaps instead of Latest being a separate reduction in Core, we want to remove it and add a new type ``Latest : Nat -> Type -> Type`` with ``pushLatest : Latest n t -> t -> Latest n t`` and ``readLatest : Latest n t -> Array t``.
However this ``pushLatest`` is only really allowed in a fold/reduction, and the value pushed needs to be a function of the current fact of the stream - you aren't allowed to put a fold accumulator inside a latest, because the bubblegum would need more than just the current fact.

Maybe the push is actually impure and only allowed in reduction: ``pushLatest : Latest n t -> Reduction ()``.
We'd also want ``makeLatest : Latest n t`` to construct buffers.
Then, reading is only possible in postcomputations: ``readLatest : Latest n t -> Post (Array t)``.

This would allow us to do latests over groups, and I believe the bubblegum semantics would make sense.
It complicates Core a little bit, but I don't think it will complicate the actual conversions to and from Core too much.

**Comment by amosr** [comment]
yay, @tranma fixed this
