### ISSUE TITLE
Get and Seq Functions

### ISSUE THREAD

**Issue by HuwCampbell** [ambiata/icicle#162]
These aren't really possible to write in the prelude satisfactorily.
`Get :: Option a -> a` takes a stream of options, and turns it into a stream of possibilities. Working on said stream will be just like working on a normal one, but now None looks like a tombstone.
`Seq:: a -> b -> b` forces evaluation of a, causing computation to fail on a tombstone even if it otherwise wouldn't (for example, if you're calculation was purely on the dates of the stream, one could seq over the value to ensure that it would fail sensibly).

**Comment by amosr** [comment]
Yep, sounds good.
Implementing some of these will require a modification to ReifyPossibilities: https://github.com/ambiata/icicle/blob/master/src/Icicle/Source/Transform/ReifyPossibility.hs#L208
Because it currently assumes that if you apply a Possibly to a function, it has to unwrap the possibly before applying the function, and returning the result.
For now it is probably easiest to just add a special case for the "get" function and whatnot.

We need the other direction for get, too.
```
boxOption :: Definitely (Option a) -> Possibly a
boxSum :: Definitely (Sum Error a) -> Possibly a
unboxOption :: Possibly a -> Definitely (Option a)
unboxSum :: Possibly a -> Definitely (Sum Error a)

throw err = boxSum (Left err)
```
get, wrap, unwrap, catch, possibly, unpossible… whatever pair of names works.

I think ``seq`` is actually only useful in a Possibly context, so I was first tempted that its type should be
```
seq :: Possibly a -> Possibly b -> Possibly b
```
but I guess you want to use it inside ``count``, which should be polymorphic. so yeah, ``seq`` should just be ``a -> b -> b``.

**Comment by HuwCampbell** [comment]
Seq, is done. I think I'll park Get temporarily.
