### ISSUE TITLE
prevent some bound variables from appearing in fold zeros

### ISSUE THREAD

**Issue by tranma** [ambiata/icicle#86]
I'm introducing a construct where a new name is bound before a let-fold:

```
feature salary ~> group fold (k, foo) = (group date ~> count) ~> let fold s = 42 : foo + s ~> s
```

But if the user uses `foo` instead of 42 in the foldZero:

```
feature salary ~> group fold (k, foo) = (group date ~> count) ~> let fold s = foo : foo + s ~> s
```

This is syntactically ok and type correct, but I'm not sure what the semantics should be. The generated Core isn't well-typed because `foo` is mentioned where it's not in scope.

I saw this happening because the inliner inlines functions like `sum`

```
feature salary ~> group fold (k, foo) = (group date ~> count) ~> sum foo
==>
feature salary ~> group fold (k, foo) = (group date ~> count) ~> let x = foo ~> let fold s = 0 : foo + s ~> s
```

The Core gen pushes the `let x = foo` inside the zero of the fold, triggering this problem... I'm not sure how to handle this, @amosr ?

**Comment by tranma** [comment]
actually, looks like you've already fixed it in the Source checker. Just needed the right temporality for the new bindings!

**Comment by amosr** [comment]
Sorry in advance for brevity.

Yep, the temporality of the initial of a fold should be Pure, and the foo should be Element. So using foo should not be allowed to happen in the initial because it'd force it to be Element.
However - it may very well be that removing the bindings is equivalent and gives better error messages.

But you're right - having the Element temporality should fix it :point_right:

**Comment by tranma** [comment]
temporality feels like poor man's linear types? :money_with_wings:

**Comment by amosr** [comment]
umm. well, kind of. linear logic and the temporality are both kinds of modal logic, so there's definitely some relation. yeah, I guess it is very similar
